### PR TITLE
feat: line numbers plugin

### PR DESCRIPTION
**Pull request by gumingWu**

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Maybe the `use-mdx` doc should be updated as well.

**Comment by gumingWu** [comment]
> Maybe the `use-mdx` doc should be updated as well.
I have doubts about this, what needs to be updated

**Comment by sanyuan0704** [comment]
@gumingWu You can go ahead `docs/zh/guide/use-mdx` and `docs/en/guide/use-mdx` file to add the content.

**Comment by sanyuan0704** [comment]
Maybe you should rebase the master because i found some irrelevant commit in this pr.

**Review by sanyuan0704 — APPROVED** [review]

**Review by sanyuan0704 — APPROVED** [review]

**Pull request merged**
