### PR TITLE
docs: back top

### PR DESCRIPTION
**Pull request by Przeblysk**

### CODE REVIEW

**Comment by sanyuan0704** [comment]
Why the dep should be add additionally?

**Comment by liuqh0609** [comment]
> Why the dep should be add additionally?

I think it's because `@iconify-json/carbon ` is currently in `devDependencies` and that's why it doesn't work properly with icons after packaging

**Comment by liuqh0609** [comment]
image

Check out the details:  https://liuqh-note.netlify.app/note/hmr-vite.html

**Comment by sanyuan0704** [comment]
#115 has solved it.

**Pull request closed without merging**
